### ISSUE TITLE
oauth error  -  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by Haizanjs** [teamreflex/discord-oauth#25] opened 2018-04-17 18:59 UTC
After I do the oauth and use the redirect uri 👍 
**'redirectUri'  => 'http://localhost:63342/whoscrypto/discord_test.php',**

this is the error I get.

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\whoscrypto\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186 Stack trace: #0 C:\xampp\htdocs\whoscrypto\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\whoscrypto\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\whoscrypto\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\whoscrypto\vend in C:\xampp\htdocs\whoscrypto\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

**Comment by Lachee** [comment] 2018-06-18 12:15
I had this issue to and a quick google of `cURL error 60: SSL certificate problem` had the stackoverflow https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

The marked solution works. Basically you don't have SSL setup properly on your dev environment.  

This is also a duplicate of issue #18

**Closed as completed** 2018-12-14 15:54 UTC
